const http=require('http');const fs=require('fs');const path=require('path');const WebSocket=require('ws');const PORT=process.env.PORT||10000;const publicDir=path.join(__dirname,'public');const rooms=new Map();
const WEAPONS={paint:{name:'Paint Blaster',damage:20,rate:1}};const EPIC=[];const CHARACTERS=['Maya','Zara','Nova','Skye','Jax','Rico','Kai','Dante'];
const server=http.createServer((req,res)=>{let pathname=(req.url||'/').split('?')[0];if(pathname==='/')pathname='/index.html';const file=path.join(publicDir,pathname);if(!file.startsWith(publicDir))return res.writeHead(403).end();fs.readFile(file,(err,data)=>{if(err)return res.writeHead(404).end('Not found');const ext=path.extname(file);const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};let out=data;if(pathname==='/index.html'){let html=data.toString();html=html.replace('</body>',`<script src="/characters.js"></script><script src="/graphics.js"></script><script src="/mobile-controls-fix.js"></script></body>`);out=Buffer.from(html);}res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream',...(pathname==='/index.html'?{'Cache-Control':'no-store, no-cache, must-revalidate, max-age=0'}:{})});res.end(out);});});
const wss=new WebSocket.Server({server});function send(ws,d){if(ws&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(d));}function broadcast(r,d){for(const p of r.players.values())send(p.ws,d);}function state(r){return{type:'state',players:[...r.players.values()].map(p=>({id:p.id,name:p.name,character:p.character,x:p.x,y:p.y,hp:p.hp,color:p.color,alive:p.alive,weapon:p.weapon,kills:p.kills,paintHits:p.paintHits,hellfire:false,dragonRider:p.dragonRider,mounted:p.mounted,epic:null,abilityReady:p.abilityReady,abilityCooldown:p.abilityCooldown,isBot:!!p.isBot})),mode:'paintball',started:r.started,round:r.round,boss:null,prep:false,eliteZombies:[],rules:r.rules};}function roomState(r){broadcast(r,state(r));}function code(){let c;do c=Math.random().toString(36).slice(2,6).toUpperCase();while(rooms.has(c));return c;}
function normalizeRules(x){const cooldown=Math.max(180,Math.min(300,Number(x?.cooldownSeconds)||180));return{mode:'paintball',players:Math.max(2,Math.min(16,Number(x?.players)||8)),time:Math.max(5,Math.min(30,Number(x?.time)||10)),score:Math.max(1,Math.min(100,Number(x?.score)||20)),respawn:x?.respawn!==false,cooldown,dragon:false,rides:true,private:x?.private!==false};}
function reset(r){let i=0;r.round++;for(const p of r.players.values()){p.x=160+(i%4)*180;p.y=160+Math.floor(i/4)*180;p.hp=100;p.alive=true;p.mounted=false;p.abilityReady=true;p.abilityCooldown=0;i++;}r.started=true;r.boss=null;r.eliteZombies=[];roomState(r);}
function makePlayer(id,m,ws,x,y){return{id,name:m.name||'Player',character:CHARACTERS.includes(m.character)?m.character:'Maya',x,y,hp:100,color:'#'+Math.floor(Math.random()*16777215).toString(16).padStart(6,'0'),alive:true,ws,weapon:'paint',kills:0,paintHits:0,hellfire:false,dragonRider:false,mounted:false,epic:null,abilityReady:true,abilityCooldown:0,isBot:false};}
function addBot(r){if(r.botId)return;const id='bot-practice';const bot=makePlayer(id,{name:'Practice Bot',character:'Jax'},null,940,520);bot.isBot=true;bot.color='#ff7a2f';r.botId=id;r.players.set(id,bot);roomState(r);}
function runBot(r){if(!r.started||!r.botId)return;const bot=r.players.get(r.botId);if(!bot||!bot.alive)return;const humans=[...r.players.values()].filter(p=>!p.isBot&&p.alive);if(!humans.length)return;const target=humans[0];const dx=target.x-bot.x,dy=target.y-bot.y,dist=Math.hypot(dx,dy);if(dist>110){const step=7;bot.x=Math.max(35,Math.min(1165,bot.x+dx/dist*step));bot.y=Math.max(35,Math.min(665,bot.y+dy/dist*step));}else if(Math.random()<0.18){target.hp=Math.max(0,target.hp-5);bot.paintHits++;if(target.hp===0){target.hp=100;target.alive=true;bot.kills++;}roomState(r);return;}roomState(r);}
setInterval(()=>{for(const r of rooms.values())runBot(r)},120);
wss.on('connection',ws=>{const id=Math.random().toString(36).slice(2,9);ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}
if(m.type==='create'){const r={code:code(),mode:'paintball',rules:normalizeRules(m.rules),started:false,round:0,prep:false,players:new Map(),boss:null,eliteZombies:[],botId:null};rooms.set(r.code,r);const p=makePlayer(id,m,ws,160,160);r.players.set(id,p);ws.room=r;ws.pid=id;addBot(r);send(ws,{type:'joined',code:r.code,id,rules:r.rules});roomState(r);}
else if(m.type==='join'){const r=rooms.get((m.code||'').toUpperCase());if(!r||r.players.size>=r.rules.players)return send(ws,{type:'error',message:'Room unavailable'});const n=r.players.size;const p=makePlayer(id,m,ws,160+(n%4)*180,160+Math.floor(n/4)*180);r.players.set(id,p);ws.room=r;ws.pid=id;send(ws,{type:'joined',code:r.code,id,rules:r.rules});roomState(r);}
else if(m.type==='setRules'&&ws.room&&!ws.room.started){ws.room.rules=normalizeRules(m.rules);roomState(ws.room);}
else if(m.type==='start'&&ws.room)reset(ws.room);
else if(m.type==='weapon'&&ws.room){const p=ws.room.players.get(ws.pid);if(!p)return;if(m.weapon!=='paint')return;p.weapon='paint';roomState(ws.room);}
else if(m.type==='move'&&ws.room){const p=ws.room.players.get(ws.pid);if(!p||!p.alive)return;p.x=Math.max(35,Math.min(1165,Number(m.x)||p.x));p.y=Math.max(35,Math.min(665,Number(m.y)||p.y));roomState(ws.room);}
else if(m.type==='jump'&&ws.room){const r=ws.room,p=r.players.get(ws.pid);if(!p||!p.alive)return;p.y=Math.max(35,p.y-35);roomState(r);setTimeout(()=>{if(r.players.has(p.id)&&p.alive){p.y=Math.min(665,p.y+35);roomState(r)}},260);}
else if(m.type==='ability'&&ws.room){const r=ws.room,p=r.players.get(ws.pid);if(!p||!p.alive||!p.abilityReady)return;p.abilityReady=false;p.abilityCooldown=r.rules.cooldown;roomState(r);setTimeout(()=>{p.abilityReady=true;p.abilityCooldown=0;roomState(r)},r.rules.cooldown*1000);}
else if(m.type==='shoot'&&ws.room){const r=ws.room,sh=r.players.get(ws.pid);if(!sh||!sh.alive)return;const hit=r.players.get(m.target);if(hit&&hit.alive&&hit.id!==sh.id){hit.hp=Math.max(0,hit.hp-WEAPONS.paint.damage);sh.paintHits++;if(hit.hp<=0){hit.alive=false;sh.kills++;if(sh.paintHits>=10&&r.rules.rides)sh.dragonRider=true;if(r.rules.respawn)setTimeout(()=>{if(r.players.has(hit.id)){hit.hp=100;hit.alive=true;hit.mounted=false;roomState(r)}},3000);}roomState(r);}}
else if(m.type==='rideDragon'&&ws.room){const r=ws.room,p=r.players.get(ws.pid);if(p&&p.dragonRider&&r.rules.rides)p.mounted=!p.mounted;roomState(r);}
});ws.on('close',()=>{const r=ws.room;if(r){r.players.delete(ws.pid);if(!r.players.size)rooms.delete(r.code);else roomState(r);}});});server.listen(PORT,'0.0.0.0',()=>console.log(`PAINTFALL listening on ${PORT}`));