const http=require('http');const fs=require('fs');const path=require('path');const WebSocket=require('ws');const PORT=process.env.PORT||10000;const publicDir=path.join(__dirname,'public');const rooms=new Map();
const WEAPONS={paint:{name:'Paint Blaster',damage:20,rate:1},ak:{name:'AK Neon',damage:28,rate:1.7},ak_ember:{name:'AK Ember',damage:32,rate:1.5},tommy:{name:'Tommy Classic',damage:16,rate:3},tommy_chrome:{name:'Tommy Chrome',damage:19,rate:2.7},mac11:{name:'MAC-11 Blaster',damage:22,rate:3.4},glock:{name:'Glock Blaster',damage:24,rate:2.2},switchblade:{name:'Switchblade Blaster',damage:38,rate:1.8},blackice:{name:'Black Ice Cooler',damage:34,rate:1.2},hellfire:{name:'Rainbow HELLFIRE',damage:48,rate:1.4}};
const EPIC=['ak_ember','tommy_chrome','mac11','glock','switchblade','blackice','hellfire'];const CHARACTERS=['Maya','Zara','Nova','Skye','Jax','Rico','Kai','Dante'];
const BOT_PROFILES=[{name:'Milo',role:'Scout',character:'Jax',weapon:'paint',emoji:'🧭',aggression:.55},{name:'Tessa',role:'Guardian',character:'Zara',weapon:'paint',emoji:'🛡️',aggression:.45},{name:'Ando',role:'Tactician',character:'Kai',weapon:'paint',emoji:'🧠',aggression:.5},{name:'Blaze',role:'Rusher',character:'Dante',weapon:'paint',emoji:'⚡',aggression:.85},{name:'Ziggy',role:'Trickster',character:'Nova',weapon:'paint',emoji:'🕵️',aggression:.65}];
const server=http.createServer((req,res)=>{let pathname=(req.url||'/').split('?')[0];if(pathname==='/')pathname='/index.html';const file=path.join(publicDir,pathname);if(!file.startsWith(publicDir))return res.writeHead(403).end();fs.readFile(file,(err,data)=>{if(err)return res.writeHead(404).end('Not found');const ext=path.extname(file);const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};let out=data;if(pathname==='/index.html'){let html=data.toString();html=html.replace('</head>',`<script type="module" src="/maya-3d.js"></script></head>`);html=html.replace('</style>','body{touch-action:auto;overflow-y:auto;-webkit-overflow-scrolling:touch;}main{padding-bottom:190px}@media(max-width:700px){main{padding-bottom:220px}}#controls{touch-action:none}</style>');html=html.replace('</body>',`<div id="extraWeapons" style="margin-top:8px;display:flex;gap:7px;flex-wrap:wrap"><button onclick="chooseWeapon('mac11')">⚡ MAC-11</button><button onclick="chooseWeapon('glock')">🔵 Glock</button><button onclick="chooseWeapon('switchblade')">🗡️ Switchblade Blaster</button><button onclick="chooseWeapon('blackice')">❄️ Black Ice</button></div><div id="epicHint" style="margin-top:8px;color:#c7b9ff;font-size:12px">Dragon Survival: creepy elite zombies can award a random Epic weapon. HELLFIRE stays with you until you are eliminated.</div><script src="/characters.js"></script><script src="/graphics.js"></script><script src="/paintfall-character-roster.js"></script><script src="/paintfall-character-selection.js"></script><script src="/paintfall-character-animation-foundation.js"></script><script src="/paintfall-character-models.js"></script><script src="/paintfall-hero-brain.js"></script><script src="/paintfall-hero-visible-tells.js"></script><script src="/paintfall-visible-brain-ui.js"></script><script src="/paintfall-create-chaos.js"></script><script src="/paintfall-party-preview.js"></script><script src="/paintfall-match-transition.js"></script></body>`);out=Buffer.from(html);}res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});res.end(out);});});
const wss=new WebSocket.Server({server});function send(ws,d){if(ws&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(d));}function broadcast(r,d){for(const p of r.players.values())if(p.ws)send(p.ws,d);}function humanCount(r){let n=0;for(const p of r.players.values())if(!p.bot)n++;return n;}function state(r){return{type:'state',players:[...r.players.values()].map(p=>({id:p.id,name:p.name,character:p.character,x:p.x,y:p.y,z:p.z||0,hp:p.hp,color:p.color,alive:p.alive,weapon:p.weapon,kills:p.kills,paintHits:p.paintHits,hellfire:p.hellfire,dragonRider:p.dragonRider,mounted:p.mounted,epic:p.epic,abilityReady:p.abilityReady,abilityCooldown:p.abilityCooldown,bot:!!p.bot,profile:p.profile||null,role:p.role||null,emoji:p.emoji||null})),mode:r.mode,started:r.started,round:r.round,boss:r.boss,prep:r.prep,eliteZombies:r.eliteZombies,rules:r.rules};}function roomState(r){broadcast(r,state(r));}function code(){let c;do c=Math.random().toString(36).slice(2,6).toUpperCase();while(rooms.has(c));return c;}
function normalizeRules(x,mode){const cooldown=Math.max(180,Math.min(300,Number(x?.cooldownSeconds)||180));return{mode:mode||'paintball',players:Math.max(2,Math.min(16,Number(x?.players)||8)),time:Math.max(5,Math.min(30,Number(x?.time)||10)),score:Math.max(1,Math.min(100,Number(x?.score)||20)),respawn:x?.respawn!==false,cooldown,dragon:!!x?.dragon,rides:x?.rides!==false,private:x?.private!==false,bots:Math.max(0,Math.min(15,Number(x?.bots)||0)),humanPlayers:Math.max(1,Math.min(16,Number(x?.humanPlayers)||1))};}
function makePlayer(id,m,ws,x,y){return{id,name:m.name||'Player',character:CHARACTERS.includes(m.character)?m.character:'Maya',x,y,z:0,vz:0,grounded:true,hp:100,color:'#'+Math.floor(Math.random()*16777215).toString(16).padStart(6,'0'),alive:true,ws,bot:false,weapon:'paint',kills:0,paintHits:0,hellfire:false,dragonRider:false,mounted:false,epic:null,abilityReady:true,abilityCooldown:0,nextThink:0,nextShot:0,respawnAt:0};}
function makeBot(index,profile){const p=profile||BOT_PROFILES[index%BOT_PROFILES.length];return{id:`bot-${p.name.toLowerCase()}-${Math.random().toString(36).slice(2,6)}`,name:p.name,character:p.character,role:p.role,emoji:p.emoji,profile:p.name,x:160+(index%4)*180,y:160+Math.floor(index/4)*180,z:0,vz:0,grounded:true,hp:100,color:'#'+Math.floor(Math.random()*16777215).toString(16).padStart(6,'0'),alive:true,ws:null,bot:true,weapon:p.weapon,kills:0,paintHits:0,hellfire:false,dragonRider:false,mounted:false,epic:null,abilityReady:true,abilityCooldown:0,nextThink:0,nextShot:0,respawnAt:0,aggression:p.aggression};}
function syncBots(r){const humans=humanCount(r);const maxBots=Math.max(0,r.rules.players-humans);const desired=Math.min(r.rules.bots,maxBots);const bots=[...r.players.values()].filter(p=>p.bot);while(bots.length>desired){const b=bots.pop();r.players.delete(b.id);}for(let i=bots.length;i<desired;i++)r.players.set(`bot-${i}-${Math.random().toString(36).slice(2,5)}`,makeBot(i,BOT_PROFILES[i%BOT_PROFILES.length]));}
function reset(r){syncBots(r);let i=0;r.round++;for(const p of r.players.values()){p.x=160+(i%4)*180;p.y=160+Math.floor(i/4)*180;p.z=0;p.vz=0;p.grounded=true;p.hp=100;p.alive=true;p.mounted=false;p.abilityReady=true;p.abilityCooldown=0;p.respawnAt=0;p.nextThink=0;p.nextShot=0;i++;}r.started=true;r.prep=r.mode==='zombies'&&r.round<4;r.boss=r.mode==='zombies'&&!r.prep?{hp:1400,x:600,y:350,defeated:false,lava:[]}:null;r.eliteZombies=r.mode==='zombies'?[{name:'Creeper',x:260,y:160,weapon:EPIC[Math.floor(Math.random()*EPIC.length)]},{name:'Grim Walker',x:940,y:160,weapon:EPIC[Math.floor(Math.random()*EPIC.length)]},{name:'Nightmare',x:600,y:540,weapon:EPIC[Math.floor(Math.random()*EPIC.length)]}]:[];if(r.mode==='zombies'&&!r.prep&&r.players.size){const ps=[...r.players.values()];const lucky=ps[Math.floor(Math.random()*ps.length)];const reward=EPIC[Math.floor(Math.random()*EPIC.length)];lucky.epic=reward;if(reward==='hellfire')lucky.hellfire=true;}roomState(r);}
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}function nearestHuman(r,bot){let best=null,bestD=Infinity;for(const p of r.players.values())if(!p.bot&&p.alive){const d=distance(bot,p);if(d<bestD){best=p;bestD=d;}}return best;}
function botShoot(r,bot,target){const now=Date.now();if(now<bot.nextShot||!target||!target.alive)return;const weapon=WEAPONS[bot.weapon]||WEAPONS.paint;const range=bot.weapon==='paint'?360:420;if(distance(bot,target)>range)return;bot.nextShot=now+1000/Math.max(.5,weapon.rate);target.hp=Math.max(0,target.hp-weapon.damage);if(bot.weapon==='paint')bot.paintHits++;if(target.hp<=0){target.alive=false;bot.kills++;if(r.mode==='zombies')target.hellfire=false;if(r.mode==='paintball'&&bot.paintHits>=10&&r.rules.rides)bot.dragonRider=true;if(r.rules.respawn&&r.mode!=='zombies')target.respawnAt=now+3000;} }
function updateBots(r){if(!r.started)return;const now=Date.now();let changed=false;for(const bot of r.players.values()){if(!bot.bot)continue;if(!bot.alive){if(bot.respawnAt&&now>=bot.respawnAt&&r.rules.respawn&&r.mode!=='zombies'){bot.hp=100;bot.alive=true;bot.respawnAt=0;bot.x=160+Math.floor(Math.random()*5)*180;bot.y=160+Math.floor(Math.random()*3)*170;changed=true;}continue;}const target=nearestHuman(r,bot);if(!target)continue;const dx=target.x-bot.x,dy=target.y-bot.y,d=Math.max(1,Math.hypot(dx,dy));const profile=BOT_PROFILES.find(p=>p.name===bot.profile)||BOT_PROFILES[0];const desired=profile.name==='Rusher'?120:profile.name==='Scout'?260:190;const speed=profile.name==='Rusher'?8:profile.name==='Guardian'?5:6;if(d>desired){bot.x=Math.max(35,Math.min(1165,bot.x+dx/d*speed));bot.y=Math.max(35,Math.min(665,bot.y+dy/d*speed));changed=true;}else if(d<90&&profile.name!=='Rusher'){bot.x=Math.max(35,Math.min(1165,bot.x-dx/d*3));bot.y=Math.max(35,Math.min(665,bot.y-dy/d*3));changed=true;}botShoot(r,bot,target);if(bot.hp<=0){bot.hp=0;bot.alive=false;bot.respawnAt=r.rules.respawn&&r.mode!=='zombies'?now+3000:0;changed=true;}}if(changed)roomState(r);}
setInterval(()=>{for(const r of rooms.values())updateBots(r);},250);
setInterval(()=>{for(const r of rooms.values()){let changed=false;for(const p of r.players.values()){if(!p.alive||p.grounded)continue;p.z+=p.vz;p.vz-=0.022;if(p.z<=0){p.z=0;p.vz=0;p.grounded=true;}changed=true;}if(changed)roomState(r);}},50);
function scheduleRoomCleanup(r){if(r.cleanupTimer)return;r.cleanupTimer=setTimeout(()=>{if(humanCount(r)===0){rooms.delete(r.code);}else r.cleanupTimer=null;},15000);}
function cancelRoomCleanup(r){if(r.cleanupTimer){clearTimeout(r.cleanupTimer);r.cleanupTimer=null;}}
wss.on('connection',ws=>{const id=Math.random().toString(36).slice(2,9);ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}
if(m.type==='create'){const r={code:code(),mode:m.mode||'paintball',rules:normalizeRules(m.rules,m.mode||'paintball'),started:false,round:0,prep:false,players:new Map(),boss:null,eliteZombies:[],cleanupTimer:null};rooms.set(r.code,r);const p=makePlayer(id,m,ws,160,160);r.players.set(id,p);syncBots(r);ws.room=r;ws.pid=id;cancelRoomCleanup(r);send(ws,{type:'joined',code:r.code,id,rules:r.rules});roomState(r);}
else if(m.type==='join'){const r=rooms.get((m.code||'').toUpperCase());if(!r||humanCount(r)>=r.rules.players)return send(ws,{type:'error',message:'Room unavailable'});const n=humanCount(r);const p=makePlayer(id,m,ws,160+(n%4)*180,160+Math.floor(n/4)*180);r.players.set(id,p);cancelRoomCleanup(r);ws.room=r;ws.pid=id;send(ws,{type:'joined',code:r.code,id,rules:r.rules});roomState(r);}
else if(m.type==='setRules'&&ws.room&&!ws.room.started){ws.room.rules=normalizeRules(m.rules,ws.room.mode);syncBots(ws.room);roomState(ws.room);}
else if(m.type==='start'&&ws.room)reset(ws.room);
else if(m.type==='weapon'&&ws.room){const p=ws.room.players.get(ws.pid);if(!p)return;const w=m.weapon;if(ws.room.mode==='paintball'&&w!=='paint')return;if(w==='hellfire'&&!p.hellfire)return;if(WEAPONS[w])p.weapon=w;roomState(ws.room);}
else if(m.type==='move'&&ws.room){const p=ws.room.players.get(ws.pid);if(!p||!p.alive)return;p.x=Math.max(35,Math.min(1165,Number(m.x)||p.x));p.y=Math.max(35,Math.min(665,Number(m.y)||p.y));roomState(ws.room);}
else if(m.type==='jump'&&ws.room){const r=ws.room,p=r.players.get(ws.pid);if(!p||!p.alive||p.mounted||!p.grounded)return;p.grounded=false;p.vz=0.19;roomState(r);}
else if(m.type==='ability'&&ws.room){const r=ws.room,p=r.players.get(ws.pid);if(!p||!p.alive||!p.abilityReady)return;p.abilityReady=false;p.abilityCooldown=r.rules.cooldown;roomState(r);setTimeout(()=>{if(r.players.has(p.id)){p.abilityReady=true;p.abilityCooldown=0;roomState(r);}},r.rules.cooldown*1000);}
else if(m.type==='shoot'&&ws.room){const r=ws.room,sh=r.players.get(ws.pid);if(!sh||!sh.alive)return;const w=WEAPONS[sh.weapon]||WEAPONS.paint;const hit=r.players.get(m.target);if(hit&&hit.alive&&hit.id!==sh.id){hit.hp=Math.max(0,hit.hp-w.damage);if(sh.weapon==='paint')sh.paintHits++;if(hit.hp<=0){hit.alive=false;sh.kills++;if(r.mode==='zombies')hit.hellfire=false;if(r.mode==='paintball'&&sh.paintHits>=10&&r.rules.rides)sh.dragonRider=true;if(r.rules.respawn&&r.mode!=='zombies')hit.respawnAt=Date.now()+3000;}roomState(r);}}
else if(m.type==='bossHit'&&ws.room&&ws.room.boss&&ws.room.rules.dragon){const r=ws.room,p=r.players.get(ws.pid);if(!p||!p.alive)return;const w=WEAPONS[p.weapon]||WEAPONS.paint;r.boss.hp=Math.max(0,r.boss.hp-w.damage);if(r.boss.hp===0)r.boss.defeated=true;roomState(r);}
else if(m.type==='rideDragon'&&ws.room){const r=ws.room,p=r.players.get(ws.pid);if(p&&r.mode==='paintball'&&p.dragonRider&&r.rules.rides)p.mounted=!p.mounted;roomState(r);}
});ws.on('close',()=>{const r=ws.room;if(r){r.players.delete(ws.pid);if(humanCount(r)===0)scheduleRoomCleanup(r);else roomState(r);}});});server.listen(PORT,'0.0.0.0',()=>console.log(`PAINTFALL listening on ${PORT}`));