import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {WebSocketServer,WebSocket} from 'ws';
const publicDir=path.join(process.cwd(),'public');const rooms=new Map<string,any>();
const WEAPONS:any={paint:{name:'Paint Blaster',damage:20,rate:1},ak:{name:'AK-Style Blaster',damage:28,rate:1.7},tommy:{name:'Tommy Blaster',damage:16,rate:3},hellfire:{name:'HELLFIRE',damage:45,rate:1.4}};
const server=http.createServer((req,res)=>{let pathname=(req.url||'/').split('?')[0];if(pathname==='/')pathname='/index.html';const file=path.join(publicDir,pathname);if(!file.startsWith(publicDir))return res.writeHead(403).end();fs.readFile(file,(err,data)=>{if(err)return res.writeHead(404).end('Not found');const ext=path.extname(file);const types:any={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});res.end(data);});});
const wss=new WebSocketServer({server});function send(ws:WebSocket,d:any){if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(d));}function broadcast(r:any,d:any){for(const p of r.players.values())send(p.ws,d);}function state(r:any){return{type:'state',players:[...r.players.values()].map((p:any)=>({id:p.id,name:p.name,x:p.x,y:p.y,hp:p.hp,color:p.color,alive:p.alive,weapon:p.weapon,kills:p.kills,paintHits:p.paintHits,hellfire:p.hellfire,dragonRider:p.dragonRider,mounted:p.mounted})),mode:r.mode,started:r.started,round:r.round,boss:r.boss,prep:r.prep};}function roomState(r:any){broadcast(r,state(r));}function code(){let c:string;do c=Math.random().toString(36).slice(2,6).toUpperCase();while(rooms.has(c));return c;}
function reset(r:any){let i=0;r.round++;for(const p of r.players.values()){p.x=160+(i%4)*180;p.y=160+Math.floor(i/4)*180;p.hp=100;p.alive=true;p.mounted=false;if(r.mode==='zombies'&&r.round>=3)p.hellfire=true;i++;}r.started=true;r.prep=r.mode==='zombies'&&r.round<4;r.boss=r.mode==='zombies'&&!r.prep?{hp:1400,x:600,y:350,defeated:false,lava:[]}:null;roomState(r);}
function makePlayer(id:string,m:any,ws:WebSocket,x:number,y:number){return{id,name:m.name||'Player',x,y,hp:100,color:'#'+Math.floor(Math.random()*16777215).toString(16).padStart(6,'0'),alive:true,ws,weapon:'paint',kills:0,paintHits:0,hellfire:false,dragonRider:false,mounted:false};}
wss.on('connection',ws=>{const id=Math.random().toString(36).slice(2,9);ws.on('message',raw=>{let m:any;try{m=JSON.parse(raw.toString())}catch{return}
if(m.type==='create'){const r={code:code(),mode:m.mode||'paintball',started:false,round:0,prep:false,players:new Map(),boss:null};rooms.set(r.code,r);const p=makePlayer(id,m,ws,160,160);r.players.set(id,p);(ws as any).room=r;(ws as any).pid=id;send(ws,{type:'joined',code:r.code,id});roomState(r);}
else if(m.type==='join'){const r=rooms.get((m.code||'').toUpperCase());if(!r||r.players.size>=8)return send(ws,{type:'error',message:'Room unavailable'});const n=r.players.size;const p=makePlayer(id,m,ws,160+(n%4)*180,160+Math.floor(n/4)*180);r.players.set(id,p);(ws as any).room=r;(ws as any).pid=id;send(ws,{type:'joined',code:r.code,id});roomState(r);}
else if(m.type==='start'&&(ws as any).room)reset((ws as any).room);
else if(m.type==='weapon'&&(ws as any).room){const r=(ws as any).room,p=r.players.get((ws as any).pid);if(!p)return;const w=m.weapon;if(w==='hellfire'&&!p.hellfire)return;if(WEAPONS[w])p.weapon=w;roomState(r);}
else if(m.type==='move'&&(ws as any).room){const r=(ws as any).room,p=r.players.get((ws as any).pid);if(!p||!p.alive)return;p.x=Math.max(35,Math.min(1165,Number(m.x)||p.x));p.y=Math.max(35,Math.min(665,Number(m.y)||p.y));roomState(r);}
else if(m.type==='shoot'&&(ws as any).room){const r=(ws as any).room,sh=r.players.get((ws as any).pid);if(!sh||!sh.alive)return;const w=WEAPONS[sh.weapon]||WEAPONS.paint;const hit=r.players.get(m.target);if(hit&&hit.alive&&hit.id!==sh.id){hit.hp-=w.damage;if(sh.weapon==='paint')sh.paintHits++;if(hit.hp<=0){hit.hp=0;hit.alive=false;sh.kills++;if(r.mode==='paintball'&&sh.paintHits>=10)sh.dragonRider=true;}roomState(r);}}
else if(m.type==='bossHit'&&(ws as any).room&&(ws as any).room.boss){const r=(ws as any).room,p=r.players.get((ws as any).pid);if(!p||!p.alive)return;const w=WEAPONS[p.weapon]||WEAPONS.paint;r.boss.hp=Math.max(0,r.boss.hp-w.damage);if(r.boss.hp===0)r.boss.defeated=true;roomState(r);}
else if(m.type==='rideDragon'&&(ws as any).room){const r=(ws as any).room,p=r.players.get((ws as any).pid);if(p&&r.mode==='paintball'&&p.dragonRider)p.mounted=!p.mounted;roomState(r);}
});ws.on('close',()=>{const r=(ws as any).room;if(r){r.players.delete((ws as any).pid);if(!r.players.size)rooms.delete(r.code);else roomState(r);}});});
export default server;
